### Ndarray: Heart of Numpy ==>array()

In [ ]:
import numpy as np

l =[1, 2, 3]

n_arr = np.array(l)
n_arr

### check type of object

In [ ]:
type(n_arr)

### know associated dtype

In [ ]:
n_arr.dtype

### obtain ndim, shape and size 

In [ ]:
n_arr.ndim, n_arr.shape, n_arr.size

In [ ]:
n_arr_2d= np.array([[1,'x',3],[3, 4, 5]])
n_arr_2d

In [ ]:
n_arr_2d.ndim, n_arr_2d.shape, n_arr_2d.size, n_arr_2d.dtype

In [ ]:
n_arr_2d.ndim, n_arr_2d.shape, n_arr_2d.size, n_arr_2d.dtype

### itemsize==> defines the size in bytes of each item in the array

In [ ]:
n_arr_2d.itemsize, n_arr_2d.dtype

In [ ]:
l1 = [1, 2, 3]
l2 = [4, 5, 6]
n_arr_2 = np.array([[l1, l2]])

In [ ]:
n_arr_2.itemsize, n_arr_2.dtype

### creating an array  
                       a. through list
                       b. through tuples
                       c. sequences of tuples and interconnected lists

In [ ]:
nd_arr = np.array([[1, 2, 3], [4, 5, 6]])
nd_arr

In [ ]:
nd_arr = np.array(((1, 2, 3), (4, 5, 6)))
nd_arr

In [ ]:
nd_arr = np.array([(1, 2, 3), [4, 5, 6]])
nd_arr

### array creation with set of internal function
    zeros()
    ones()
    arange()
    linspace()
    random()

In [ ]:
np.zeros((3,3))

In [ ]:
np.ones((3,3))

In [ ]:
np.arange(1,6)

In [ ]:
np.arange(1,12,2)

In [ ]:
np.arange(1,-12,-2)

In [ ]:
np.arange(0,12).reshape(6,2) # 6 dimension 2 elements

In [ ]:
np.linspace(0, 10, 5) # third argument: # of interval to be equally distributed

In [ ]:
np.random.random((3,2))

### Basic Operations

    arithmetic operations
    matrix product
    increment and decrement operators
    universal functions
    aggregate functions
    

In [ ]:
n_arr = np.arange(4)
n_arr

In [ ]:
n_arr + 5

In [ ]:
n_arr * 5

In [ ]:
n_arr_2 = np.arange(5, 9)
n_arr_2

In [ ]:
n_arr + n_arr_2 # element-wise operations

In [ ]:
n_arr - n_arr_2

In [ ]:
n_arr * n_arr_2

In [ ]:
n_arr / n_arr_2

In [ ]:
n_arr * np.sin(n_arr_2)

In [ ]:
n_arr * np.sqrt(n_arr_2)

### Matrix Product

In [ ]:
A = np.arange(0, 9).reshape(3,3)
A

In [ ]:
B = np.ones((3,3))
B

In [ ]:
A * B

In [ ]:
np.dot(A,B)

In [ ]:
np.dot(B, A)

In [ ]:
A.dot(B)

In [ ]:
B.dot(A)

### INCREMENT and DECREMENT OPERATORS

### +=, -=
    instead of creating a new array they reassign the result to the same

In [ ]:
arr = np.arange(4)
arr

In [ ]:
arr +=1
arr

In [ ]:
arr -= 1
arr

### Universal Functions (ufunc)

function operating of an array in an element by element fashion
output: an array of same size (as of input)

In [ ]:
# sqrt() log() sin
import numpy as np
arr = np.arange(1, 5)
arr

In [ ]:
np.sqrt(arr)

In [ ]:
np.log(arr)

In [ ]:
np.sin(arr)

### Aggregate functions
 produce single results

In [ ]:
arr.sum()

In [ ]:
arr.min(), arr.max()

In [ ]:
arr.mean(), arr.std()

### Indexing , Slicing and Iterating

In [ ]:
arr = np.arange(10, 16)
arr

In [ ]:
arr[3]

In [ ]:
# also accepts -ve int
arr[-3]

In [ ]:
arr[1], arr[-1]

In [ ]:
arr[[1, 3, 5]]

In [ ]:
arr[[-1, -3, -5]]

In [ ]:
ARR = np.arange(10, 19).reshape((3,3))
ARR

In [ ]:
ARR[0,2]

In [ ]:
ARR[[0,2]]

### Slicing

    list : copies
    numpy array: views
    make use of the slice: colon(:)

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(10, 20)
arr

In [ ]:
arr[1:5] # last index -1

    extract from array by skipping some items

In [ ]:
arr[1:5:2]

In [ ]:
# other examples

arr[::2]

In [ ]:
arr[:5:2]

In [ ]:
arr[:5:]

##### 2-D Array

In [ ]:
A = np.arange(10,19).reshape(3,3)
A

In [ ]:
A[0, :]

In [ ]:
A[:,1]

In [ ]:
A[0:2, 1:2]

In [ ]:
A[[0,2], 0:2]

In [ ]:
A[[0,2], 0:3]

### Iterating an Array

In [ ]:
for i in A:
    print(i)

In [ ]:
# iteration element by element
for row in A.flat:
    print(row)

In [ ]:
# apply_along_axis()

import numpy as np

np.apply_along_axis(np.mean, axis=0, arr=A)

In [ ]:
# axis 1 row by row
# axis 0 column
np.apply_along_axis(np.mean, axis=1, arr=A)

In [ ]:
def div_by_2(x):
    return x/2


np.apply_along_axis(div_by_2, axis=1, arr=A)

### Conditional and Boolean Arrays

In [ ]:
arr = np.arange(5)
arr

In [ ]:
arr>3

In [ ]:
arr[arr>3]

In [ ]:
arr!=3

In [ ]:
arr[arr!=3]

In [ ]:
# element wise comparison of two arrays
(2 * arr)==(arr)

In [ ]:
arr[(2 * arr)==(arr)]

In [ ]:
(2 * arr) == (4 * arr)

In [ ]:
arr[(2 * arr) == (4 + arr)]

In [ ]:
arr_rand = np.random.RandomState(0)
arr_rand = arr_rand.randint(10, size=(3,4))
arr_rand

In [ ]:
arr_rand[arr_rand < 6]

In [ ]:
np.count_nonzero(arr_rand < 6)

In [ ]:
np.sum(arr_rand < 6)

In [ ]:
np.sum(arr_rand < 6, axis = 1) #row

In [ ]:
np.sum(arr_rand < 6, axis = 0) 

In [ ]:
np.any(arr_rand > 5) # boolean

In [ ]:
np.all(arr_rand <5)

In [ ]:
np.all(arr_rand <6, axis =1)

In [ ]:
np.sum((arr_rand < 6 ) & ( arr_rand >4), axis = 0)

In [ ]:
np.sum(~(arr_rand <= 6 ) | (arr_rand >= 1) )

### Shape Manipulation

In [ ]:
import numpy as np
a = np.random.random(12)
a

In [ ]:
A = a.reshape(3, 4)
A

In [ ]:
a.shape = (4,3)

In [ ]:
a

In [ ]:
##ravel(): converts 2D array into 1D
a = a.ravel()
a

In [ ]:
a.shape = (12)
a

In [ ]:
##transpose: invert columns with rows
A

In [ ]:
A.transpose()

### Array Manipulation

In [ ]:
# vstack: joins array vertically rather stacks them 

ONE = np.ones((3,3))
ONE

In [ ]:
ZERO = np.zeros((3,4))
ZERO

In [ ]:
np.vstack((ONE, ZERO))

In [ ]:
#hstack : joins array horizontally rather stacks them 
np.hstack((ONE, ZERO))

In [ ]:
#used with one-dimensional arrays
#column_stack: stacks as columns to form 2D arrays
#row_stack: stacks as rows to form 2D arrays

arr_1 = np.array([0, 1, 2])
arr_2 = np.array([3, 4, 5])
arr_3 = np.array([6, 7, 8])

np.column_stack((arr_1, arr_2, arr_3))

In [ ]:
np.row_stack((arr_1, arr_2, arr_3))

## Splitting Array

In [ ]:
# vsplit: 
#hsplit:

## Copied or Views of Objects

In [ ]:
a = np.array([1, 2, 3, 4])
a

In [ ]:
b=a
b

In [ ]:
a[2]=6
b

In [ ]:
a

In [ ]:
# slicing
c = a[0:2]
c

In [ ]:
a[0] =0
c

In [ ]:
# copy(): to generate a complete copy and distinct array

a = np.array([1, 2, 3, 4])
a

In [ ]:
c = a.copy()
c

In [ ]:
a[0]=0
a

In [ ]:
c

## Vectorization

In [ ]:
# The vectorization is the absence of explicit loop
# vectorization leads to a more concise and readable code
# operations take on a more mathematical expression using vectorization


In [ ]:
a * b

In [ ]:
A = np.arange(1,10)
A

In [ ]:
A = A.reshape(3,3)

In [ ]:
B = np.arange(9)
B = B.reshape(3,3)

In [ ]:
A * B

In [ ]:
for(i=0; i<rows; i++)
{
    for(j=0; j<columns; j++)
    {
        c[i][j]=a[i][j]*b[i][j];
    }
}

## Broadcasting

In [ ]:
# Broadcasting allows an operator or function to act on 
#two or more arrays to operate even if these arrays do not have same shape and size

#Rules applied::
#  1. All dimensions are compatible
#  2. one of the dimension must be equal to 1



In [ ]:
import numpy as np

x = np.array([[0, 0, 0],[10,10,10],[20,20,20]])
x

In [ ]:
y=np.array([1,2,3])
y

In [ ]:
x + y

In [15]:
x = np.array([[0], [10], [20]])
x

array([[ 0],
       [10],
       [20]])

In [16]:
y

array([1, 2, 3])

In [17]:
x.shape, y.shape

((3, 1), (3,))

In [18]:
x+y

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23]])

## Loading and Saving Data in Binary Files

In [ ]:
# save() and load function

In [ ]:
import numpy as np

In [ ]:
data = np.arange(0,16).reshape(8, 2)

In [ ]:
data

In [ ]:
np.save('saved_data', data)

In [ ]:
load_data = np.load('saved_data.npy')
load_data

## Reading Files with Tabular Data

In [ ]:
#loadtxt
#genfromtxt

In [ ]:
FILENAME = "/Users/nvishwakarma/Downloads/athena_data/stats/_2018-02-20.csv"

In [ ]:
import numpy as np
np.loadtxt(FILENAME, delimiter=',', skiprows=1)

In [ ]:
np.genfromtxt(FILENAME, delimiter=',')

In [ ]:
# genfromtxt

data = np.genfromtxt(FILENAME, delimiter=",", names = True)
data

### Numpy Memory Management

In [ ]:
import numpy as np

In [ ]:
array_x = np.array([100.45, 83.24, 874.12, 98.123])

In [ ]:
array_x.dtype

In [ ]:
#bool_, int_, intc, intp, int8, 
#int16, int32, int64, uint8, uint16, uint32, uint64, float_, float16, float32, float64, complex_, complex64

In [ ]:
np.sctypes

In [ ]:
# check parent class of data types
np.float32.mro()

In [ ]:
np.complex256.mro()

In [ ]:
#check size


In [ ]:
np.float32(100.13).nbytes

In [ ]:
np.float64(100.13).nbytes

In [ ]:
array_x2 = array_x.astype(np.float32)

In [ ]:
array_x2

In [ ]:
np.float32(array_x2).nbytes

In [ ]:
np.float64(array_x).nbytes

In [ ]:
# __array_interface__

In [ ]:
array_x.__array_interface__

In [ ]:
E = np.array([1,2,3,2,1,3,9,8,11,12,10,11,14,25,26,24,30,22,24,27])

In [ ]:
E[::4]

In [ ]:
nd_arr_1 = np.random.randn(4, 6, 8)
nd_arr_1

In [ ]:
nd_arr_2 = nd_arr_1[::, ::2, ::3]

In [ ]:
nd_arr_2

In [ ]:
nd_arr_1.__array_interface__

In [ ]:
nd_arr_2.__array_interface__

In [ ]:
import numpy as np
nd_arr_1 = np.random.randn(400, 600)
nd_arr_1

In [ ]:
nd_arr_2 = np.random.randn(400, 300*40)[::, ::20]

In [ ]:
nd_arr_1.shape, nd_arr_2.shape

In [ ]:
%%timeit
np.cumprod(nd_arr_1)

In [ ]:
%%timeit
np.cumprod(nd_arr_2)

In [ ]:
nd_arr_1.__array_interface__

In [ ]:
nd_arr_2.__array_interface__

In [ ]:
import numexpr as ne

In [ ]:
%%timeit
2 * nd_arr_1 +56